#!/usr/bin/env python3
from ros_web_gui.app import create_app
import os
import pkg_resources
import yaml

if __name__ == "__main__":
    # Read config file
    config_file = pkg_resources.resource_filename('ros_web_gui', 'config/config.yaml')
    with open(config_file, 'r') as stream:
        try:
            config = yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            print(exc)

    flask_app = create_app(config)
    flask_app.run()